name = "j"  # Specify the name of your worker
type = "javascript"        # Specify the worker type (e.g., "javascript", "webpack", "rust")

main = "src/index.js"      # Specify the entry point script for your worker

account_id = "4806f2425c6560e67d083f843b83dd5d"  # Your Cloudflare account ID
workers_dev = true         # Set to true if using Cloudflare Workers Dev mode
compatibility_date = "2024-11-24"  # Specify the compatibility date for the worker

# Bind KV namespace
kv_namespaces = [
  { binding = "KEYS_NAMESPACE", id = "74d6b52c378740db9e43d7ad6172304a" }
]

# Optional: Configuring logging
[observability.logs]
enabled = true  # Enable log observability
